# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.12 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================

CXX = g++

CPPDEPS = -MT$@ -MF$@.d -MD -MP

OBJS = gcc_mswu

ACCESSTEST_CXXFLAGS = -O2 -mthreads -D__WXMSW__ -DNDEBUG -D_UNICODE -I.\..\..\lib\gcc_lib\mswu -I.\..\..\include \
	-W -Wall -I.\..\..\samples -DNOPCH -Wno-ctor-dtor-privacy

ACCESSTEST_OBJECTS = $(OBJS)\accesstest_sample_rc.o $(OBJS)\accesstest_accesstest.o

all: $(OBJS)
$(OBJS):
	-if not exist $(OBJS) mkdir $(OBJS)

all: $(OBJS)\accesstest.exe

clean: 
	-if exist $(OBJS)\*.o del $(OBJS)\*.o
	-if exist $(OBJS)\*.d del $(OBJS)\*.d
	-if exist $(OBJS)\accesstest.exe del $(OBJS)\accesstest.exe

$(OBJS)\accesstest.exe: $(ACCESSTEST_OBJECTS) $(OBJS)\accesstest_sample_rc.o
	$(foreach f, $(subst \,/,$(ACCESSTEST_OBJECTS)), $(shell echo $f >> $(subst \,/,$@).rsp.tmp))
	@move /y $@.rsp.tmp $@.rsp >nul
	$(CXX) -o $@ @$@.rsp -mthreads -L .\..\..\lib\gcc_lib  -Wl,--subsystem,windows -mwindows -lwxmsw31u_core -lwxbase31u -lwxtiff -lwxjpeg -lwxpng -lwxzlib -lwxregexu -lwxexpat -lkernel32 -luser32 -lgdi32 -lcomdlg32 -lwinspool -lwinmm -lshell32 -lshlwapi -lcomctl32 -lole32 -loleaut32 -luuid -lrpcrt4 -ladvapi32 -lversion -lwsock32 -lwininet -loleacc -luxtheme
	del $@.rsp

$(OBJS)\accesstest_sample_rc.o: ./sample.rc
	windres -i$< -o$@  --define __WXMSW__ --define NDEBUG --define _UNICODE --include-dir .\..\..\lib\gcc_lib\mswu --include-dir ./../../include --include-dir . --define wxUSE_DPI_AWARE_MANIFEST=2 --include-dir ./../../samples --define NOPCH

$(OBJS)\accesstest_accesstest.o: ./accesstest.cpp
	$(CXX) -c -o $@ $(ACCESSTEST_CXXFLAGS) $(CPPDEPS) $<

.PHONY: all clean

# Dependencies tracking:
-include $(OBJS)/*.d
